### ISSUE TITLE
Inappropriate code 

### ISSUE THREAD

**Issue by IamChiranjeeviR** [rasheedt9x/Basic-Programs#2]
Hello Mr Rasheed, actually your code is good. But you have done initializing the patterns. do it in another way without initializing the patterns........... you are becoming "DON"......

**Comment by rasheedt9x** [comment]
Here you go Mr Chiranjeevi now you can take input during runtime
[New Text Document (3).txt](https://github.com/rasheedt9x/Basic-Programs/files/11856481/New.Text.Document.3.txt)

**Comment by rasheedt9x** [comment]
Hope your issue is clear now. Do you have any other issues?
